<?xml version="1.0"?>
    <robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find fishbot_description)/urdf/fishibot/common_inertia.xacro"/>

        <xacro:macro name="base_xacro" params="length radius">
            <!-- 声明地面 -->
            <link name="base_footprint" />
            
            <!-- 机器人的身体部分 -->
            <link name="base_link">
                <!-- 部件的外观描述 -->
                <visual>
                    <!-- 沿着本体几何中心的偏移量和旋转量 -->
                    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                    <!-- 几何形状 -->
                    <geometry>
                        <!-- 圆柱体 radius 半径0.10m 高度 length 0.12m -->
                        <cylinder radius="${radius}" length="${length}"/>
                    </geometry>
                    <!-- 材质颜色 -->
                    <material name="white">
                        <color rgba="1.0 1.0 1.0 0.5"/>
                    </material>
                </visual>
                
                <collision>
                    <!-- 沿着本体几何中心的偏移量和旋转量 -->
                    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                    <!-- 几何形状 -->
                    <geometry>
                        <!-- 圆柱体 radius 半径0.10m 高度 length 0.12m -->
                        <cylinder radius="${radius}" length="${length}"/>
                    </geometry>
                    <!-- 材质颜色 -->
                    <material name="white">
                        <color rgba="1.0 1.0 1.0 0.5"/>
                    </material>
                </collision>
                <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}" />
            </link>

            <!-- 地面位置 base_link高度的一半+轮半径 -0.001为了更贴合地面 -->
            <joint name="joint_name" type="fixed">
                <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
                <parent link="base_footprint"/>
                <child link="base_link"/>
            </joint>

        </xacro:macro>
    </robot>